# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(default=None, related_name='favorites', to='quote.Quote'),
        ),
    ]
